#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *
from thrift.Thrift import TProcessor
from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class Iface:
  """
  Order-book replay service
  """
  def replay(self, assetId, variables, startDateTime, endDateTime):
    """
    Replay tick events


    Parameters:
     - assetId
     - variables
     - startDateTime
     - endDateTime
    """
    pass

  def shuffledReplay(self, assetId, variables, proportionShuffling, windowSize, intraWindow, offsetting, attribute):
    """
    Parameters:
     - assetId
     - variables
     - proportionShuffling
     - windowSize
     - intraWindow
     - offsetting
     - attribute
    """
    pass

  def shuffledReplayDateRange(self, assetId, variables, proportionShuffling, windowSize, intraWindow, offsetting, attribute, startDateTime, endDateTime):
    """
    Parameters:
     - assetId
     - variables
     - proportionShuffling
     - windowSize
     - intraWindow
     - offsetting
     - attribute
     - startDateTime
     - endDateTime
    """
    pass


class Client(Iface):
  """
  Order-book replay service
  """
  def __init__(self, iprot, oprot=None):
    self._iprot = self._oprot = iprot
    if oprot is not None:
      self._oprot = oprot
    self._seqid = 0

  def replay(self, assetId, variables, startDateTime, endDateTime):
    """
    Replay tick events


    Parameters:
     - assetId
     - variables
     - startDateTime
     - endDateTime
    """
    self.send_replay(assetId, variables, startDateTime, endDateTime)
    return self.recv_replay()

  def send_replay(self, assetId, variables, startDateTime, endDateTime):
    self._oprot.writeMessageBegin('replay', TMessageType.CALL, self._seqid)
    args = replay_args()
    args.assetId = assetId
    args.variables = variables
    args.startDateTime = startDateTime
    args.endDateTime = endDateTime
    args.write(self._oprot)
    self._oprot.writeMessageEnd()
    self._oprot.trans.flush()

  def recv_replay(self):
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
    if mtype == TMessageType.EXCEPTION:
      x = TApplicationException()
      x.read(self._iprot)
      self._iprot.readMessageEnd()
      raise x
    result = replay_result()
    result.read(self._iprot)
    self._iprot.readMessageEnd()
    if result.success is not None:
      return result.success
    raise TApplicationException(TApplicationException.MISSING_RESULT, "replay failed: unknown result");

  def shuffledReplay(self, assetId, variables, proportionShuffling, windowSize, intraWindow, offsetting, attribute):
    """
    Parameters:
     - assetId
     - variables
     - proportionShuffling
     - windowSize
     - intraWindow
     - offsetting
     - attribute
    """
    self.send_shuffledReplay(assetId, variables, proportionShuffling, windowSize, intraWindow, offsetting, attribute)
    return self.recv_shuffledReplay()

  def send_shuffledReplay(self, assetId, variables, proportionShuffling, windowSize, intraWindow, offsetting, attribute):
    self._oprot.writeMessageBegin('shuffledReplay', TMessageType.CALL, self._seqid)
    args = shuffledReplay_args()
    args.assetId = assetId
    args.variables = variables
    args.proportionShuffling = proportionShuffling
    args.windowSize = windowSize
    args.intraWindow = intraWindow
    args.offsetting = offsetting
    args.attribute = attribute
    args.write(self._oprot)
    self._oprot.writeMessageEnd()
    self._oprot.trans.flush()

  def recv_shuffledReplay(self):
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
    if mtype == TMessageType.EXCEPTION:
      x = TApplicationException()
      x.read(self._iprot)
      self._iprot.readMessageEnd()
      raise x
    result = shuffledReplay_result()
    result.read(self._iprot)
    self._iprot.readMessageEnd()
    if result.success is not None:
      return result.success
    raise TApplicationException(TApplicationException.MISSING_RESULT, "shuffledReplay failed: unknown result");

  def shuffledReplayDateRange(self, assetId, variables, proportionShuffling, windowSize, intraWindow, offsetting, attribute, startDateTime, endDateTime):
    """
    Parameters:
     - assetId
     - variables
     - proportionShuffling
     - windowSize
     - intraWindow
     - offsetting
     - attribute
     - startDateTime
     - endDateTime
    """
    self.send_shuffledReplayDateRange(assetId, variables, proportionShuffling, windowSize, intraWindow, offsetting, attribute, startDateTime, endDateTime)
    return self.recv_shuffledReplayDateRange()

  def send_shuffledReplayDateRange(self, assetId, variables, proportionShuffling, windowSize, intraWindow, offsetting, attribute, startDateTime, endDateTime):
    self._oprot.writeMessageBegin('shuffledReplayDateRange', TMessageType.CALL, self._seqid)
    args = shuffledReplayDateRange_args()
    args.assetId = assetId
    args.variables = variables
    args.proportionShuffling = proportionShuffling
    args.windowSize = windowSize
    args.intraWindow = intraWindow
    args.offsetting = offsetting
    args.attribute = attribute
    args.startDateTime = startDateTime
    args.endDateTime = endDateTime
    args.write(self._oprot)
    self._oprot.writeMessageEnd()
    self._oprot.trans.flush()

  def recv_shuffledReplayDateRange(self):
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
    if mtype == TMessageType.EXCEPTION:
      x = TApplicationException()
      x.read(self._iprot)
      self._iprot.readMessageEnd()
      raise x
    result = shuffledReplayDateRange_result()
    result.read(self._iprot)
    self._iprot.readMessageEnd()
    if result.success is not None:
      return result.success
    raise TApplicationException(TApplicationException.MISSING_RESULT, "shuffledReplayDateRange failed: unknown result");


class Processor(Iface, TProcessor):
  def __init__(self, handler):
    self._handler = handler
    self._processMap = {}
    self._processMap["replay"] = Processor.process_replay
    self._processMap["shuffledReplay"] = Processor.process_shuffledReplay
    self._processMap["shuffledReplayDateRange"] = Processor.process_shuffledReplayDateRange

  def process(self, iprot, oprot):
    (name, type, seqid) = iprot.readMessageBegin()
    if name not in self._processMap:
      iprot.skip(TType.STRUCT)
      iprot.readMessageEnd()
      x = TApplicationException(TApplicationException.UNKNOWN_METHOD, 'Unknown function %s' % (name))
      oprot.writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
      x.write(oprot)
      oprot.writeMessageEnd()
      oprot.trans.flush()
      return
    else:
      self._processMap[name](self, seqid, iprot, oprot)
    return True

  def process_replay(self, seqid, iprot, oprot):
    args = replay_args()
    args.read(iprot)
    iprot.readMessageEnd()
    result = replay_result()
    result.success = self._handler.replay(args.assetId, args.variables, args.startDateTime, args.endDateTime)
    oprot.writeMessageBegin("replay", TMessageType.REPLY, seqid)
    result.write(oprot)
    oprot.writeMessageEnd()
    oprot.trans.flush()

  def process_shuffledReplay(self, seqid, iprot, oprot):
    args = shuffledReplay_args()
    args.read(iprot)
    iprot.readMessageEnd()
    result = shuffledReplay_result()
    result.success = self._handler.shuffledReplay(args.assetId, args.variables, args.proportionShuffling, args.windowSize, args.intraWindow, args.offsetting, args.attribute)
    oprot.writeMessageBegin("shuffledReplay", TMessageType.REPLY, seqid)
    result.write(oprot)
    oprot.writeMessageEnd()
    oprot.trans.flush()

  def process_shuffledReplayDateRange(self, seqid, iprot, oprot):
    args = shuffledReplayDateRange_args()
    args.read(iprot)
    iprot.readMessageEnd()
    result = shuffledReplayDateRange_result()
    result.success = self._handler.shuffledReplayDateRange(args.assetId, args.variables, args.proportionShuffling, args.windowSize, args.intraWindow, args.offsetting, args.attribute, args.startDateTime, args.endDateTime)
    oprot.writeMessageBegin("shuffledReplayDateRange", TMessageType.REPLY, seqid)
    result.write(oprot)
    oprot.writeMessageEnd()
    oprot.trans.flush()


# HELPER FUNCTIONS AND STRUCTURES

class replay_args:
  """
  Attributes:
   - assetId
   - variables
   - startDateTime
   - endDateTime
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'assetId', None, None, ), # 1
    (2, TType.LIST, 'variables', (TType.STRING,None), None, ), # 2
    (3, TType.I64, 'startDateTime', None, None, ), # 3
    (4, TType.I64, 'endDateTime', None, None, ), # 4
  )

  def __init__(self, assetId=None, variables=None, startDateTime=None, endDateTime=None,):
    self.assetId = assetId
    self.variables = variables
    self.startDateTime = startDateTime
    self.endDateTime = endDateTime

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.assetId = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.LIST:
          self.variables = []
          (_etype3, _size0) = iprot.readListBegin()
          for _i4 in xrange(_size0):
            _elem5 = iprot.readString();
            self.variables.append(_elem5)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I64:
          self.startDateTime = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.I64:
          self.endDateTime = iprot.readI64();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('replay_args')
    if self.assetId is not None:
      oprot.writeFieldBegin('assetId', TType.STRING, 1)
      oprot.writeString(self.assetId)
      oprot.writeFieldEnd()
    if self.variables is not None:
      oprot.writeFieldBegin('variables', TType.LIST, 2)
      oprot.writeListBegin(TType.STRING, len(self.variables))
      for iter6 in self.variables:
        oprot.writeString(iter6)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.startDateTime is not None:
      oprot.writeFieldBegin('startDateTime', TType.I64, 3)
      oprot.writeI64(self.startDateTime)
      oprot.writeFieldEnd()
    if self.endDateTime is not None:
      oprot.writeFieldBegin('endDateTime', TType.I64, 4)
      oprot.writeI64(self.endDateTime)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class replay_result:
  """
  Attributes:
   - success
  """

  thrift_spec = (
    (0, TType.MAP, 'success', (TType.STRING,None,TType.LIST,(TType.DOUBLE,None)), None, ), # 0
  )

  def __init__(self, success=None,):
    self.success = success

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 0:
        if ftype == TType.MAP:
          self.success = {}
          (_ktype8, _vtype9, _size7 ) = iprot.readMapBegin()
          for _i11 in xrange(_size7):
            _key12 = iprot.readString();
            _val13 = []
            (_etype17, _size14) = iprot.readListBegin()
            for _i18 in xrange(_size14):
              _elem19 = iprot.readDouble();
              _val13.append(_elem19)
            iprot.readListEnd()
            self.success[_key12] = _val13
          iprot.readMapEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('replay_result')
    if self.success is not None:
      oprot.writeFieldBegin('success', TType.MAP, 0)
      oprot.writeMapBegin(TType.STRING, TType.LIST, len(self.success))
      for kiter20,viter21 in self.success.items():
        oprot.writeString(kiter20)
        oprot.writeListBegin(TType.DOUBLE, len(viter21))
        for iter22 in viter21:
          oprot.writeDouble(iter22)
        oprot.writeListEnd()
      oprot.writeMapEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class shuffledReplay_args:
  """
  Attributes:
   - assetId
   - variables
   - proportionShuffling
   - windowSize
   - intraWindow
   - offsetting
   - attribute
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'assetId', None, None, ), # 1
    (2, TType.LIST, 'variables', (TType.STRING,None), None, ), # 2
    (3, TType.DOUBLE, 'proportionShuffling', None, None, ), # 3
    (4, TType.I32, 'windowSize', None, None, ), # 4
    (5, TType.BOOL, 'intraWindow', None, None, ), # 5
    (6, TType.I32, 'offsetting', None, None, ), # 6
    (7, TType.I32, 'attribute', None, None, ), # 7
  )

  def __init__(self, assetId=None, variables=None, proportionShuffling=None, windowSize=None, intraWindow=None, offsetting=None, attribute=None,):
    self.assetId = assetId
    self.variables = variables
    self.proportionShuffling = proportionShuffling
    self.windowSize = windowSize
    self.intraWindow = intraWindow
    self.offsetting = offsetting
    self.attribute = attribute

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.assetId = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.LIST:
          self.variables = []
          (_etype26, _size23) = iprot.readListBegin()
          for _i27 in xrange(_size23):
            _elem28 = iprot.readString();
            self.variables.append(_elem28)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.DOUBLE:
          self.proportionShuffling = iprot.readDouble();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.I32:
          self.windowSize = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.BOOL:
          self.intraWindow = iprot.readBool();
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.I32:
          self.offsetting = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.I32:
          self.attribute = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('shuffledReplay_args')
    if self.assetId is not None:
      oprot.writeFieldBegin('assetId', TType.STRING, 1)
      oprot.writeString(self.assetId)
      oprot.writeFieldEnd()
    if self.variables is not None:
      oprot.writeFieldBegin('variables', TType.LIST, 2)
      oprot.writeListBegin(TType.STRING, len(self.variables))
      for iter29 in self.variables:
        oprot.writeString(iter29)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.proportionShuffling is not None:
      oprot.writeFieldBegin('proportionShuffling', TType.DOUBLE, 3)
      oprot.writeDouble(self.proportionShuffling)
      oprot.writeFieldEnd()
    if self.windowSize is not None:
      oprot.writeFieldBegin('windowSize', TType.I32, 4)
      oprot.writeI32(self.windowSize)
      oprot.writeFieldEnd()
    if self.intraWindow is not None:
      oprot.writeFieldBegin('intraWindow', TType.BOOL, 5)
      oprot.writeBool(self.intraWindow)
      oprot.writeFieldEnd()
    if self.offsetting is not None:
      oprot.writeFieldBegin('offsetting', TType.I32, 6)
      oprot.writeI32(self.offsetting)
      oprot.writeFieldEnd()
    if self.attribute is not None:
      oprot.writeFieldBegin('attribute', TType.I32, 7)
      oprot.writeI32(self.attribute)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class shuffledReplay_result:
  """
  Attributes:
   - success
  """

  thrift_spec = (
    (0, TType.MAP, 'success', (TType.STRING,None,TType.LIST,(TType.DOUBLE,None)), None, ), # 0
  )

  def __init__(self, success=None,):
    self.success = success

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 0:
        if ftype == TType.MAP:
          self.success = {}
          (_ktype31, _vtype32, _size30 ) = iprot.readMapBegin()
          for _i34 in xrange(_size30):
            _key35 = iprot.readString();
            _val36 = []
            (_etype40, _size37) = iprot.readListBegin()
            for _i41 in xrange(_size37):
              _elem42 = iprot.readDouble();
              _val36.append(_elem42)
            iprot.readListEnd()
            self.success[_key35] = _val36
          iprot.readMapEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('shuffledReplay_result')
    if self.success is not None:
      oprot.writeFieldBegin('success', TType.MAP, 0)
      oprot.writeMapBegin(TType.STRING, TType.LIST, len(self.success))
      for kiter43,viter44 in self.success.items():
        oprot.writeString(kiter43)
        oprot.writeListBegin(TType.DOUBLE, len(viter44))
        for iter45 in viter44:
          oprot.writeDouble(iter45)
        oprot.writeListEnd()
      oprot.writeMapEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class shuffledReplayDateRange_args:
  """
  Attributes:
   - assetId
   - variables
   - proportionShuffling
   - windowSize
   - intraWindow
   - offsetting
   - attribute
   - startDateTime
   - endDateTime
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'assetId', None, None, ), # 1
    (2, TType.LIST, 'variables', (TType.STRING,None), None, ), # 2
    (3, TType.DOUBLE, 'proportionShuffling', None, None, ), # 3
    (4, TType.I32, 'windowSize', None, None, ), # 4
    (5, TType.BOOL, 'intraWindow', None, None, ), # 5
    (6, TType.I32, 'offsetting', None, None, ), # 6
    (7, TType.I32, 'attribute', None, None, ), # 7
    (8, TType.I64, 'startDateTime', None, None, ), # 8
    (9, TType.I64, 'endDateTime', None, None, ), # 9
  )

  def __init__(self, assetId=None, variables=None, proportionShuffling=None, windowSize=None, intraWindow=None, offsetting=None, attribute=None, startDateTime=None, endDateTime=None,):
    self.assetId = assetId
    self.variables = variables
    self.proportionShuffling = proportionShuffling
    self.windowSize = windowSize
    self.intraWindow = intraWindow
    self.offsetting = offsetting
    self.attribute = attribute
    self.startDateTime = startDateTime
    self.endDateTime = endDateTime

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.assetId = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.LIST:
          self.variables = []
          (_etype49, _size46) = iprot.readListBegin()
          for _i50 in xrange(_size46):
            _elem51 = iprot.readString();
            self.variables.append(_elem51)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.DOUBLE:
          self.proportionShuffling = iprot.readDouble();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.I32:
          self.windowSize = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.BOOL:
          self.intraWindow = iprot.readBool();
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.I32:
          self.offsetting = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.I32:
          self.attribute = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 8:
        if ftype == TType.I64:
          self.startDateTime = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 9:
        if ftype == TType.I64:
          self.endDateTime = iprot.readI64();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('shuffledReplayDateRange_args')
    if self.assetId is not None:
      oprot.writeFieldBegin('assetId', TType.STRING, 1)
      oprot.writeString(self.assetId)
      oprot.writeFieldEnd()
    if self.variables is not None:
      oprot.writeFieldBegin('variables', TType.LIST, 2)
      oprot.writeListBegin(TType.STRING, len(self.variables))
      for iter52 in self.variables:
        oprot.writeString(iter52)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.proportionShuffling is not None:
      oprot.writeFieldBegin('proportionShuffling', TType.DOUBLE, 3)
      oprot.writeDouble(self.proportionShuffling)
      oprot.writeFieldEnd()
    if self.windowSize is not None:
      oprot.writeFieldBegin('windowSize', TType.I32, 4)
      oprot.writeI32(self.windowSize)
      oprot.writeFieldEnd()
    if self.intraWindow is not None:
      oprot.writeFieldBegin('intraWindow', TType.BOOL, 5)
      oprot.writeBool(self.intraWindow)
      oprot.writeFieldEnd()
    if self.offsetting is not None:
      oprot.writeFieldBegin('offsetting', TType.I32, 6)
      oprot.writeI32(self.offsetting)
      oprot.writeFieldEnd()
    if self.attribute is not None:
      oprot.writeFieldBegin('attribute', TType.I32, 7)
      oprot.writeI32(self.attribute)
      oprot.writeFieldEnd()
    if self.startDateTime is not None:
      oprot.writeFieldBegin('startDateTime', TType.I64, 8)
      oprot.writeI64(self.startDateTime)
      oprot.writeFieldEnd()
    if self.endDateTime is not None:
      oprot.writeFieldBegin('endDateTime', TType.I64, 9)
      oprot.writeI64(self.endDateTime)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class shuffledReplayDateRange_result:
  """
  Attributes:
   - success
  """

  thrift_spec = (
    (0, TType.MAP, 'success', (TType.STRING,None,TType.LIST,(TType.DOUBLE,None)), None, ), # 0
  )

  def __init__(self, success=None,):
    self.success = success

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 0:
        if ftype == TType.MAP:
          self.success = {}
          (_ktype54, _vtype55, _size53 ) = iprot.readMapBegin()
          for _i57 in xrange(_size53):
            _key58 = iprot.readString();
            _val59 = []
            (_etype63, _size60) = iprot.readListBegin()
            for _i64 in xrange(_size60):
              _elem65 = iprot.readDouble();
              _val59.append(_elem65)
            iprot.readListEnd()
            self.success[_key58] = _val59
          iprot.readMapEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('shuffledReplayDateRange_result')
    if self.success is not None:
      oprot.writeFieldBegin('success', TType.MAP, 0)
      oprot.writeMapBegin(TType.STRING, TType.LIST, len(self.success))
      for kiter66,viter67 in self.success.items():
        oprot.writeString(kiter66)
        oprot.writeListBegin(TType.DOUBLE, len(viter67))
        for iter68 in viter67:
          oprot.writeDouble(iter68)
        oprot.writeListEnd()
      oprot.writeMapEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
